[package]
name = "websocket-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
serde_json = "1.0"
uuid = { version = "1.4", features = ["v4"] }
once_cell = "1.18"
rand = "0.8"